version: "3.8"

services:
  mysql_payment:
    image: mysql:8.0
    container_name: gigs_payment_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gigs_payment
    ports:
      - "3311:3306"
    volumes:
      - payment_db_data:/var/lib/mysql

volumes:
  payment_db_data:
