// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD-ri3uAMEPgUHppn_4gAOmdn9vaSzaDHI',
//     appId: '1:960896037916:web:ae04fb2f25e45f75da5bd9',
//     messagingSenderId: '960896037916',
//     projectId: 'gigs-8b8d6',
//     authDomain: 'gigs-8b8d6.firebaseapp.com',
//     storageBucket: 'gigs-8b8d6.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBfMI16q8eS3BKAdBvC2-lEbN9xJ_NtDH0',
//     appId: '1:960896037916:android:bf531f9d7101af77da5bd9',
//     messagingSenderId: '960896037916',
//     projectId: 'gigs-8b8d6',
//     storageBucket: 'gigs-8b8d6.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC3IeLWa38pKEkTPywRPNL91Q7jmEYjnGw',
//     appId: '1:960896037916:ios:aeb2576fc2749d2cda5bd9',
//     messagingSenderId: '960896037916',
//     projectId: 'gigs-8b8d6',
//     storageBucket: 'gigs-8b8d6.firebasestorage.app',
//     iosBundleId: 'com.example.myApp',
//   );
// }
