name: ali_grad
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.5
  lottie: ^3.1.3
  font_awesome_flutter: ^10.8.0
  timeago: ^3.7.1
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  hugeicons: any
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: any
  jwt_decoder: ^2.0.1
  geocoding: ^4.0.0
  geolocator: ^11.0.0
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.15.8
  image_picker: ^1.0.4
  http: ^1.4.0
  mime: ^1.0.4
  crypto: ^3.0.3
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.3.1
  flutter_google_maps_webservices: ^1.1.1
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  # To add assets to your application, add an assets section, like this:
  #   assets:
  #     - images/a_dot_burr.jpeg
  #     - images/a_dot_ham.jpeg

