version: "3.8"
services:
  mysql_tasks:
    image: mysql:8.0
    container_name: gigs_tasks_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gigs_tasks
    ports:
      - "3308:3306"
    volumes:
      - tasks_db_data:/var/lib/mysql

volumes:
  tasks_db_data:
